"""
Shift Handoff PDF Report — generated with ReportLab.
Call generate_shift_pdf(report_dict) → returns bytes.
"""
from datetime import datetime
from io import BytesIO

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


def generate_shift_pdf(report: dict) -> bytes:
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError("reportlab not installed — add it to requirements.txt")

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.9 * inch,
        rightMargin=0.9 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title2", parent=styles["Title"], fontSize=22, spaceAfter=4, alignment=TA_CENTER)
    sub_style   = ParagraphStyle("Sub",    parent=styles["Normal"], fontSize=10, textColor=colors.grey, alignment=TA_CENTER)
    h2_style    = ParagraphStyle("H2",     parent=styles["Heading2"], fontSize=13, spaceBefore=14, spaceAfter=4)
    body_style  = styles["Normal"]

    # ── helpers ──────────────────────────────────────────────────────────────

    TEAL   = colors.HexColor("#0d9488")
    RED    = colors.HexColor("#dc2626")
    AMBER  = colors.HexColor("#d97706")
    SLATE  = colors.HexColor("#1e293b")
    LGREY  = colors.HexColor("#f1f5f9")

    def section(title):
        return [
            Spacer(1, 0.12 * inch),
            Paragraph(title, h2_style),
            HRFlowable(width="100%", thickness=1, color=TEAL, spaceAfter=6),
        ]

    def kv_table(rows: list[tuple]) -> Table:
        data = [[Paragraph(f"<b>{k}</b>", body_style), Paragraph(str(v), body_style)] for k, v in rows]
        t = Table(data, colWidths=[2.4 * inch, 4.5 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), LGREY),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LGREY]),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        return t

    def esi_table(breakdown: dict) -> Table:
        ESI_LABELS = {
            "1": ("ESI 1 — Critical",    RED),
            "2": ("ESI 2 — High Acuity", colors.HexColor("#ea580c")),
            "3": ("ESI 3 — Urgent",      AMBER),
            "4": ("ESI 4 — Less Urgent", colors.HexColor("#16a34a")),
            "5": ("ESI 5 — Non-Urgent",  colors.grey),
        }
        header = [Paragraph("<b>ESI Level</b>", body_style), Paragraph("<b>Patients</b>", body_style)]
        data = [header]
        for key in ["1", "2", "3", "4", "5"]:
            label, color = ESI_LABELS.get(key, (key, SLATE))
            count = breakdown.get(key, 0)
            data.append([
                Paragraph(f'<font color="{color.hexval()}">{label}</font>', body_style),
                Paragraph(str(count), body_style),
            ])
        t = Table(data, colWidths=[4 * inch, 2.9 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), SLATE),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ROWBACKGROUNDS", (1, 0), (-1, -1), [colors.white, LGREY]),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        return t

    # ── build story ───────────────────────────────────────────────────────────

    story = []

    # Header
    story.append(Paragraph("MediScan Gateway", title_style))
    story.append(Paragraph("Shift Handoff Report — CONFIDENTIAL", sub_style))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", sub_style))
    story.append(Spacer(1, 0.2 * inch))

    # Shift Summary
    story += section("Shift Summary")
    story.append(kv_table([
        ("Generated By",       report.get("generated_by", "Unknown")),
        ("Shift Start",        report.get("shift_start", "—")),
        ("Shift End",          report.get("shift_end", "—")),
        ("Total Patients",     report.get("total_patients", 0)),
        ("Avg Wait (min)",     f"{report.get('avg_wait_minutes', 0):.1f}"),
        ("Avg LOS (min)",      f"{report.get('report_data', {}).get('avg_los_minutes', 0):.0f}"),
        ("LWBS Rate",          f"{report.get('report_data', {}).get('lwbs_rate', 0):.1f}%"),
        ("Door-to-Triage",     f"{report.get('report_data', {}).get('door_to_triage_seconds', 0):.0f}s (target <15s)"),
    ]))

    # ESI Breakdown
    story += section("ESI Acuity Breakdown")
    story.append(esi_table(report.get("esi_breakdown", {})))

    # Clinical Alerts
    story += section("Clinical Highlights")
    story.append(kv_table([
        ("Sepsis Activations",       report.get("sepsis_count", 0)),
        ("Behavioral Health Cases",  report.get("bh_count", 0)),
        ("High LWBS Risk Patients",  report.get("lwbs_high_risk_count", 0)),
        ("Admissions Predicted",     report.get("admissions_predicted", 0)),
        ("Capacity at Shift End",    f"{report.get('report_data', {}).get('occupancy_percent', 0):.1f}%"),
        ("Boarding Patients",        report.get("report_data", {}).get("boarding_patients", 0)),
    ]))

    # Active patients snapshot
    active = report.get("report_data", {}).get("active_patients", [])
    if active:
        story += section(f"Active Patients at Handoff ({len(active)})")
        pt_header = [
            Paragraph("<b>Patient</b>", body_style),
            Paragraph("<b>ESI</b>", body_style),
            Paragraph("<b>Room</b>", body_style),
            Paragraph("<b>Chief Complaint</b>", body_style),
            Paragraph("<b>Disposition</b>", body_style),
        ]
        pt_data = [pt_header]
        for p in active[:30]:  # cap at 30 rows
            td = p.get("triage_detail", {})
            pt_data.append([
                Paragraph(p.get("name", ""), body_style),
                Paragraph(str(p.get("esi_level", "")), body_style),
                Paragraph(p.get("room_assignment", ""), body_style),
                Paragraph(p.get("chief_complaint", "")[:50], body_style),
                Paragraph(td.get("disposition_prediction", ""), body_style),
            ])
        pt_table = Table(pt_data, colWidths=[1.4*inch, 0.5*inch, 1.1*inch, 2.8*inch, 1.1*inch])
        pt_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), SLATE),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ROWBACKGROUNDS", (1, 0), (-1, -1), [colors.white, LGREY]),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(pt_table)

    # Footer note
    story.append(Spacer(1, 0.3 * inch))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph(
        "This report is protected health information (PHI) under HIPAA. "
        "Do not distribute outside authorized clinical staff.",
        ParagraphStyle("Footer", parent=body_style, fontSize=7, textColor=colors.grey, spaceAfter=0),
    ))

    doc.build(story)
    return buf.getvalue()
