"""
SOAP Note PDF generator — uses reportlab to produce a clean, printable clinical note.
"""
from datetime import datetime
from io import BytesIO

try:
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
    REPORTLAB_OK = True
except ImportError:
    REPORTLAB_OK = False


def generate_soap_pdf(note: dict, patient_name: str = "Patient") -> bytes:
    """Returns PDF bytes for a SOAP note. Falls back to plain text if reportlab unavailable."""
    if not REPORTLAB_OK:
        return _text_fallback(note, patient_name)

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=LETTER,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    teal = colors.HexColor("#0d9488")
    dark = colors.HexColor("#0f172a")
    muted = colors.HexColor("#64748b")

    title_style = ParagraphStyle(
        "Title", parent=styles["Normal"],
        fontSize=20, fontName="Helvetica-Bold",
        textColor=dark, spaceAfter=2,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontSize=10, fontName="Helvetica",
        textColor=muted, spaceAfter=4,
    )
    section_head_style = ParagraphStyle(
        "SectionHead", parent=styles["Normal"],
        fontSize=9, fontName="Helvetica-Bold",
        textColor=teal,
        spaceBefore=14, spaceAfter=4,
        textTransform="uppercase",
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontSize=10, fontName="Helvetica",
        textColor=dark, leading=15,
        spaceAfter=6,
    )
    meta_style = ParagraphStyle(
        "Meta", parent=styles["Normal"],
        fontSize=8, fontName="Helvetica",
        textColor=muted, spaceAfter=2,
    )

    now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    generated_by = note.get("generated_by", "AI")
    generated_at = note.get("generated_at", now_str)
    if isinstance(generated_at, datetime):
        generated_at = generated_at.strftime("%Y-%m-%d %H:%M UTC")

    finalized = note.get("finalized", False)
    finalized_by = note.get("finalized_by", "")

    story = []

    # Header
    story.append(Paragraph("MediScan Gateway", title_style))
    story.append(Paragraph("Clinical SOAP Note", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=teal, spaceAfter=10))

    # Patient + metadata table
    meta_rows = [
        ["Patient", patient_name, "Generated", generated_at],
        ["Generated by", generated_by, "Status",
         f"✓ Finalized by {finalized_by}" if finalized else "Draft — Pending Physician Review"],
    ]
    meta_table = Table(meta_rows, colWidths=[1.2 * inch, 2.5 * inch, 1.2 * inch, 2.5 * inch])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#64748b")),
        ("TEXTCOLOR", (2, 0), (2, -1), colors.HexColor("#64748b")),
        ("TEXTCOLOR", (1, 0), (1, -1), dark),
        ("TEXTCOLOR", (3, 0), (3, -1), dark),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=4))

    # SOAP sections
    for section_key, section_label in [
        ("subjective", "S — Subjective"),
        ("objective", "O — Objective"),
        ("assessment", "A — Assessment"),
        ("plan", "P — Plan"),
    ]:
        content = note.get(section_key, "")
        if content:
            story.append(Paragraph(section_label, section_head_style))
            # Preserve newlines as paragraphs
            for line in content.split("\n"):
                if line.strip():
                    story.append(Paragraph(line.strip(), body_style))
                else:
                    story.append(Spacer(1, 4))

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=6))

    # Footer
    footer_text = (
        f"Generated by MediScan Gateway · {now_str} · "
        "For authorized clinical use only. Not for distribution without patient consent."
    )
    story.append(Paragraph(footer_text, meta_style))

    if finalized and finalized_by:
        sig_style = ParagraphStyle(
            "Sig", parent=styles["Normal"],
            fontSize=9, fontName="Helvetica-Bold",
            textColor=teal, spaceAfter=2,
        )
        story.append(Paragraph(f"Electronically signed by: {finalized_by}", sig_style))

    doc.build(story)
    return buf.getvalue()


def _text_fallback(note: dict, patient_name: str) -> bytes:
    lines = [
        "MEDISCAN GATEWAY — CLINICAL SOAP NOTE",
        "=" * 50,
        f"Patient: {patient_name}",
        f"Generated: {note.get('generated_at', 'Unknown')}",
        f"By: {note.get('generated_by', 'AI')}",
        "",
        "SUBJECTIVE:", note.get("subjective", ""), "",
        "OBJECTIVE:", note.get("objective", ""), "",
        "ASSESSMENT:", note.get("assessment", ""), "",
        "PLAN:", note.get("plan", ""), "",
    ]
    return "\n".join(lines).encode("utf-8")
